import { describe, it, expect, afterEach, vi } from 'vitest';
import { rmSync } from 'fs';
import { join } from 'path';
import { NotesService } from '../../../electron/main/services/notes-service';

vi.mock('electron', () => ({
  app: {
    getPath: vi.fn().mockReturnValue('/tmp/test-app'),
  },
}));

const TEST_DB_PATH = join(__dirname, '__notes-test__.db');

afterEach(() => {
  try { rmSync(TEST_DB_PATH); } catch {}
  try { rmSync(TEST_DB_PATH + '-wal'); } catch {}
  try { rmSync(TEST_DB_PATH + '-shm'); } catch {}
});

describe('NotesService', () => {
  it('creates, lists, updates, deletes notes and aggregates tags', async () => {
    const { initializeDatabase } = await import('../../../electron/main/db');
    const db = initializeDatabase(TEST_DB_PATH);
    const service = new NotesService(db);

    const created = service.create({
      title: 'Meeting prep',
      content: 'Review agenda and slides',
      tags: ['work', 'meetings'],
      source: 'manual',
      pinned: true,
    });

    expect(created.title).toBe('Meeting prep');
    expect(created.pinned).toBe(true);
    expect(created.tags).toEqual(['work', 'meetings']);

    const agentNote = service.create({
      title: 'AI summary',
      content: 'Generated by assistant',
      tags: ['ai', 'work'],
      source: 'agent',
    });

    expect(agentNote.source).toBe('agent');

    const all = service.list();
    expect(all).toHaveLength(2);
    expect(all[0].id).toBe(created.id);

    const filtered = service.list({ tag: 'work' });
    expect(filtered).toHaveLength(2);

    const searched = service.list({ search: 'agenda' });
    expect(searched).toHaveLength(1);
    expect(searched[0].id).toBe(created.id);

    const tags = service.getAllTags();
    expect(tags).toEqual(['ai', 'meetings', 'work']);

    const updated = service.update(created.id, {
      title: 'Updated prep',
      pinned: false,
    });
    expect(updated.title).toBe('Updated prep');
    expect(updated.pinned).toBe(false);

    service.delete(agentNote.id);
    expect(service.list()).toHaveLength(1);

    db.close();
  });

  it('creates notes table from migration 027', async () => {
    const { initializeDatabase } = await import('../../../electron/main/db');
    const db = initializeDatabase(TEST_DB_PATH);
    const tables = db.prepare(
      "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name"
    ).all() as { name: string }[];
    const names = tables.map((t) => t.name);
    expect(names).toContain('notes');
    db.close();
  });
});
